openapi: 3.0.3
info:
  title: FX Exchange API
  description: API for fetching exchange rates, performing conversions, and retrieving conversion history.
  version: 0.1.0
servers:
  - url: /
paths:
  /rate:
    get:
      tags:
        - rates
      summary: Get current exchange rate
      operationId: getRate
      parameters:
        - name: from
          in: query
          description: Source currency code (e.g. USD)
          required: true
          schema:
            type: string
        - name: to
          in: query
          description: Target currency code (e.g. EUR)
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Current exchange rate
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ExchangeRateResponse'

  /convert:
    post:
      tags:
        - convert
      summary: Convert an amount from one currency to another
      operationId: convertCurrency
      requestBody:
        description: Conversion request payload
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ConversionRequest'
      responses:
        '200':
          description: Conversion result
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ConversionResponse'

  /history:
    get:
      tags:
        - history
      summary: Get conversion history
      operationId: getConversionHistory
      parameters:
        - name: transactionId
          in: query
          description: Filter by transaction ID
          required: false
          schema:
            type: string
            format: uuid
        - name: startDate
          in: query
          description: Filter by conversion date (YYYY-MM-DD)
          required: false
          schema:
            type: string
            format: date-time
        - name: endDate
          in: query
          description: Filter by conversion date (YYYY-MM-DD)
          required: false
          schema:
            type: string
            format: date-time
        - name: page
          in: query
          description: Page number (0-based)
          required: false
          schema:
            type: integer
            default: 0
        - name: size
          in: query
          description: Page size
          required: false
          schema:
            type: integer
            default: 20
      responses:
        '200':
          description: List of past conversions
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ConversionResponse'

components:
  schemas:
    CurrencyLayerError:
      type: object
      properties:
        code:
          type: integer
          format: int32
          description: Numeric error code returned by CurrencyLayer
        info:
          type: string
          description: Human-readable error message from CurrencyLayer
      required:
        - code
        - info
    CurrencyLayerResponse:
      type: object
      required:
        - success
        - timestamp
        - source
        - quotes
      properties:
        success:
          type: boolean
        terms:
          type: string
        privacy:
          type: string
        timestamp:
          type: integer
        source:
          type: string
        quotes:
          type: object
          additionalProperties:
            type: number
        error:
          $ref: '#/components/schemas/CurrencyLayerError'
    ExchangeRateResponse:
      type: object
      required:
        - from
        - to
        - rate
      properties:
        from:
          type: string
          description: Source currency code
        to:
          type: string
          description: Target currency code
        rate:
          type: number
          format: decimal
          description: Current exchange rate

    ConversionRequest:
      type: object
      required:
        - amount
        - from
        - to
      properties:
        amount:
          type: number
          format: decimal
          description: Amount to convert
        from:
          type: string
          pattern: '^[A-Z]{3}$'
          description: Source currency code
        to:
          type: string
          pattern: '^[A-Z]{3}$'
          description: Target currency code

    ConversionResponse:
      allOf:
        - $ref: '#/components/schemas/ConversionRequest'
        - type: object
          required:
            - convertedAmount
            - transactionId
            - timestamp
          properties:
            convertedAmount:
              type: number
              format: decimal
              description: Result of the conversion
            ratePrecision:
              type: number
              format: decimal
              description: Rate precision of the conversion
            transactionId:
              type: string
              format: uuid
              description: Unique ID for this conversion
            timestamp:
              type: string
              format: date-time
              description: Time when the conversion was performed
